"use client";

import { useEffect, useState } from "react";

type PortfolioCase = {
  number: string; title: string; label: string; summary: string; location?: string;
  images: string[]; tags: string[]; screenshots?: boolean; articleLabel: string;
  resources?: { title: string; description: string; href: string; external?: boolean }[];
  journal: { heading: string; text: string }[];
};

const imageSet=(name:string,count:number)=>Array.from({length:count},(_,i)=>`/portfolio/full/${name}-${i+1}.jpg`);

const productCases:PortfolioCase[]=[
  {number:"01",title:"Siiqo",label:"E-commerce marketplace · Lead Product Manager and Scrum Master",summary:"A trust-led marketplace designed for Nigerian buyers, vendors and service providers. It brings verified commerce, protected payments and community into one experience.",images:imageSet("siiqo",5),tags:["Escrow payments","Vendor storefronts","Community","E-bidding","Disputes","Rewards"],screenshots:true,articleLabel:"Read Siiqo case study",resources:[
    {title:"Siiqo Product Document",description:"Supporting product thinking, feature definition and delivery documentation for the Siiqo marketplace.",href:"https://docs.google.com/document/d/1SmsFGtIb60wlUKtSlwPwm8ixSl2Egf7G4-Jikkam9ko/edit?usp=drivesdk",external:true}
  ],journal:[
    {heading:"The product brief",text:"Siiqo was conceived as more than a product catalogue. The goal was to create dependable commerce infrastructure for local businesses: a place where buyers could discover products and services, assess seller credibility, pay with confidence and remain protected throughout the transaction."},
    {heading:"The problem space",text:"Trust is one of the biggest barriers in Nigerian online commerce. Buyers worry about fraudulent vendors, poor-quality items and payments made before delivery. Sellers also need visibility, practical storefront tools and reliable ways to manage orders. The product therefore had to balance buyer protection with seller growth."},
    {heading:"My responsibility",text:"As Lead Product Manager and Scrum Master, I shaped product direction, clarified the value proposition and translated the vision into a structured delivery roadmap. I led discovery, personas, journeys, PRDs, user stories, acceptance criteria, prioritisation, backlog refinement, sprint planning and cross-functional coordination across design, engineering and QA."},
    {heading:"Product decisions",text:"We centred the experience on verified sellers, escrow-secured orders and dispute protection. Around that trust layer, we developed vendor storefronts, physical and digital listings, service discovery, order management, community posts, referrals, rewards, chat and content that helps SMEs grow."},
    {heading:"Delivery approach",text:"The work was broken into connected but independently testable modules. I used continuous stakeholder alignment, clear sprint goals and acceptance criteria to reduce ambiguity. Feedback from vendors and buyers informed iteration, while QA and product reviews protected consistency across the marketplace, community and payment journeys."},
    {heading:"Outcome and learning",text:"Siiqo progressed into a live, multi-sided marketplace with a clear trust proposition and an expanding commerce ecosystem. The project reinforced that marketplace growth is not only about adding inventory. It depends on credibility, safe transactions, seller support and an experience that makes those values visible."}
  ]},
  {number:"02",title:"Canvoy Payment",label:"FinTech · Product Manager and Scrum Master",summary:"A digital payment product designed to make utility bills and everyday transactions clearer, safer and easier to complete.",images:imageSet("canvoy",2),tags:["Utility payments","MVP roadmap","Jira ownership","Scrum","Security","QA readiness"],screenshots:true,articleLabel:"Read Canvoy case study",resources:[
    {title:"Canvoy Payment 8 Week MVP Roadmap",description:"The delivery roadmap covering product discovery, design, technical setup, security, implementation and release readiness.",href:"/documents/canvoy-mvp-roadmap.pdf"}
  ],journal:[
    {heading:"The product brief",text:"Canvoy Payment set out to simplify recurring utility and everyday payments through one accessible digital experience. The MVP needed to provide confidence from registration through transaction completion while establishing a foundation that could support future payment services."},
    {heading:"The user problem",text:"Routine payments can become frustrating when platforms have confusing flows, weak status visibility or inconsistent feedback. Users need to know what is required, whether a transaction is secure, what stage it has reached and what to do when something goes wrong."},
    {heading:"My responsibility",text:"I contributed as Product Manager and Scrum Master, owning discovery, MVP definition, product requirements, prioritisation and delivery coordination. I also structured and managed the Jira workspace, turning the roadmap into epics, sprint backlogs, user stories, tasks and measurable acceptance criteria."},
    {heading:"From idea to plan",text:"The product was organised around authentication, verification, account recovery, dashboards, payment journeys, security questions, transaction feedback and profile management. I worked with design, engineering, data and cybersecurity to surface dependencies early and keep product, experience and risk decisions aligned."},
    {heading:"Agile delivery",text:"I facilitated planning, stand-ups, refinement and progress reviews, clarified requirements as questions emerged and maintained visibility across work in progress. QA readiness and risk assessment were treated as part of delivery, not activities to postpone until the end of the build."},
    {heading:"Outcome and learning",text:"The team completed a coordinated MVP definition and a delivery system that connected product decisions to design and technical execution. The experience strengthened my understanding of payment-product trust: clarity, security and timely feedback are core product features, not supporting details."}
  ]},
  {number:"03",title:"Wayagram",label:"FinTech · Social commerce · Technical Product Manager",summary:"A broad platform connecting social interaction, marketplace activity, wallets, payments and community experiences.",images:[],tags:["Wallet","Marketplace","Social feeds","KYC","Settlement","Production QA"],articleLabel:"Read Wayagram case study",resources:[
    {title:"Wayagram Product and Technical Architecture",description:"A high-level paper mapping the platform modules, service boundaries, data layer and integration approach.",href:"/documents/wayagram-product-architecture.pdf"}
  ],journal:[
    {heading:"The platform context",text:"Wayagram combined social networking, commerce and financial services in a single ecosystem. Its scope included account creation and KYC, feeds, profiles, messaging, marketplace activity, carts, orders, wallets, virtual accounts, payments, settlements, disputes and notifications."},
    {heading:"The delivery challenge",text:"The size and interdependence of the platform created a visibility problem. Work crossed multiple modules and environments, while defects in one flow could affect several downstream experiences. Production preparation required stronger ownership, regression coverage and structured reporting."},
    {heading:"My responsibility",text:"As Technical Product Manager, I coordinated production migration, regression and demo testing, QA, bug triage, staging access, daily stand-ups and module-based reporting. I helped teams connect technical readiness with the intended end-to-end user experience."},
    {heading:"Operating model",text:"I broke the platform into accountable modules and used daily priorities, ownership tracking and structured status reporting to make blockers visible. Testing focused on connected journeys rather than isolated screens, particularly where identity, wallet, marketplace and settlement services depended on each other."},
    {heading:"Product judgement",text:"My role required balancing urgency with production risk. The priority was not simply to declare features complete, but to confirm that critical user journeys behaved reliably across staging and production conditions and that unresolved issues had clear owners."},
    {heading:"Outcome and learning",text:"The approach improved delivery visibility and production-readiness tracking across a highly connected platform. It deepened my technical product-management experience in environment coordination, system dependencies, regression testing and the communication required to move complex products toward release."}
  ]}
];

const constructionCases:PortfolioCase[]=[
  {number:"01",title:"Corona School",location:"Ikoyi, Lagos",label:"Site Engineer",summary:"Structural execution and workforce coordination from foundation works through the reinforced-concrete frame.",images:imageSet("corona",7),tags:["Structural supervision","Bar-bending schedules","Drawing analysis","Quality control"],articleLabel:"Read project journal",journal:[
    {heading:"Project context",text:"The Corona School project required disciplined execution within an active urban environment. My responsibility was to translate architectural and structural information into coordinated site activity while protecting quality, sequence and programme."},{heading:"My role",text:"As Site Engineer, I supervised daily construction, interpreted structural drawings, prepared and checked bar-bending schedules, resolved drawing and reinforcement questions and coordinated artisans, labour and subcontractors."},{heading:"Execution",text:"I monitored setting-out, excavation, foundation elements, reinforcement, formwork, concrete placement and progressive frame construction. Work fronts were planned around labour, materials, inspections and the dependencies between structural and service activities."},{heading:"Leadership",text:"Clear daily instructions, checks before concrete and practical coordination helped the workforce understand priorities and reduce avoidable rework. I maintained close attention to dimensions, reinforcement details and workmanship."},{heading:"Result",text:"The structural phases advanced in an organised sequence and key milestones were achieved through detailed supervision and team coordination. The project strengthened my ability to turn technical information into reliable on-site delivery."}
  ]},
  {number:"02",title:"Kolapo Lawson Residence",location:"Ajuwon, Lagos",label:"Site Engineer",summary:"Partial demolition and reconstruction carefully joining retained building elements with new structural work.",images:imageSet("kolapo",6),tags:["Partial demolition","Reconstruction","Structural coordination","Roofing"],articleLabel:"Read project journal",journal:[
    {heading:"Project context",text:"This residential assignment involved selective demolition rather than a clean start. Existing elements had to be assessed, protected or removed before new foundations and structural components could be introduced."},{heading:"My role",text:"I coordinated demolition, interpreted the revised drawings, planned structural work, reviewed reinforcement requirements and supervised the workforce through reconstruction."},{heading:"The challenge",text:"New work had to align with retained portions of the residence. That made sequencing, dimensions and site judgement especially important because an error during demolition or interface construction could affect later stages."},{heading:"Execution",text:"I organised safe demolition zones, foundation preparation, reinforcement, concrete, blockwork and the roof structure while checking alignment between old and new construction."},{heading:"Result",text:"The reconstruction progressed from a complex altered structure into a coherent residential form. The experience strengthened my ability to manage uncertainty and coordinate renovation work where site conditions evolve as construction opens up the existing building."}
  ]},
  {number:"03",title:"Ecobank Branch",location:"Admiralty Way, Lekki Phase 1",label:"Site Engineer",summary:"A demanding commercial banking facility delivered through intensive multidisciplinary coordination and close-out management.",images:imageSet("ecobank",9),tags:["Commercial delivery","Cladding","Building services","Interior finishing"],articleLabel:"Read project journal",journal:[
    {heading:"Project context",text:"The Ecobank branch combined structural work, a distinctive façade, banking operations, interior finishes and building services within a demanding commercial programme."},{heading:"My role",text:"I supervised site execution, coordinated contractors and trades, analysed drawings, managed structural details and maintained alignment between architectural, structural and service requirements."},{heading:"The challenge",text:"The intensity increased during façade and finishing stages when multiple specialists needed access to the same work areas. Quality expectations were high and the delivery timetable required constant prioritisation."},{heading:"Execution",text:"I coordinated scaffolding, cladding, glazing, internal finishes, service interfaces, external works and outstanding items while continuing inspections and progress tracking. Decisions were communicated quickly so that one trade did not block another."},{heading:"Result",text:"The branch was delivered successfully as a functional branded facility. The project expanded my experience in commercial close-out, high-pressure coordination and managing the transition from structural construction to a polished operational environment."}
  ]},
  {number:"04",title:"Country Home",location:"Oke-Opo, Ilesa, Osun State",label:"Site Manager",summary:"End-to-end leadership of a large residential build with complex structural, masonry and roofing requirements.",images:imageSet("country",8),tags:["Site leadership","Resource planning","Residential delivery","Complex roofing"],articleLabel:"Read project journal",journal:[
    {heading:"Project context",text:"The Oke-Opo country home was a substantial residential project whose scale, location and roof geometry demanded hands-on site leadership and careful resource planning."},{heading:"My role",text:"As Site Manager, I carried responsibility for people, programme, materials, technical interpretation, quality and the coordination of all major work fronts."},{heading:"The challenge",text:"The project required dependable delivery outside Lagos, with close attention to material availability, workforce productivity and the relationship between the concrete frame, masonry and extensive roof structure."},{heading:"Execution",text:"I planned labour and materials, reviewed drawings, managed structural and blockwork activities, coordinated formwork and concrete, and supervised the progression into timber roof framing and covering."},{heading:"Result",text:"The project advanced through demanding structural and roofing milestones under coordinated site management. It reinforced my capacity to lead complex work with high accountability, especially where logistics and technical decisions must be managed together."}
  ]},
  {number:"05",title:"Pile Cap and Ground Beam Foundation",location:"Ondo Street, Banana Island, Lagos",label:"Site Engineer",summary:"A reinforcement intensive foundation package requiring accuracy in pile caps, ground beams and concrete operations.",images:imageSet("banana",5),tags:["Deep foundation","Pile caps","Ground beams","Structural QA"],articleLabel:"Read project journal",journal:[
    {heading:"Project context",text:"This Banana Island assignment focused on the substructure of a high-value development. The work demanded accuracy because pile caps and ground beams establish the load path for everything built above them."},{heading:"My role",text:"I supervised setting-out, excavation, pile-head preparation, reinforcement, formwork, concrete placement and the organisation of labour and materials."},{heading:"Technical focus",text:"The reinforcement-intensive details required close reading of structural drawings and bar schedules. I checked levels, dimensions, laps, spacing, cover and starter positions before approving work for concrete."},{heading:"Execution",text:"Activities were sequenced to keep excavation, blinding, block formwork, steel fixing and casting moving without compromising inspection. The team received clear instructions around structural tolerances and concrete readiness."},{heading:"Result",text:"The foundation package progressed with the required structural control. The project further developed my practical understanding of deep-foundation interfaces and the importance of quality assurance before permanent work is concealed."}
  ]},
  {number:"06",title:"Police Station Complex",location:"Ibeju-Lekki, Lagos",label:"Site and Project Manager",summary:"Project management of three parallel structures within one public sector development.",images:imageSet("police",12),tags:["Three structures","Project management","Resource allocation","Public infrastructure"],articleLabel:"Read project journal",journal:[
    {heading:"Project context",text:"The police station complex comprised three structures delivered within a single site. Each building had its own work fronts, but labour, materials, equipment and programme decisions had to be coordinated as one project."},{heading:"My role",text:"As Site and Project Manager, I led planning, technical coordination, workforce deployment, materials, progress control, quality checks and communication across the complex."},{heading:"The challenge",text:"Parallel construction creates competition for resources and can hide delays when attention is concentrated on one structure. The project required a clear view of dependencies and balanced allocation across foundations, frames, walls, roofs and finishes."},{heading:"Execution",text:"I organised work packages by building and milestone, coordinated reinforcement and formwork inspections, monitored concrete and blockwork, managed roofing progression and maintained visibility of constraints across the site."},{heading:"Result",text:"The three structures progressed through major structural and roofing stages under one coordinated programme. The experience demonstrated my ability to manage a multi-building development, direct several teams and maintain delivery focus across a broad site."}
  ]}
];

function Gallery({item,onZoom}:{item:PortfolioCase;onZoom:(src:string,alt:string)=>void}){if(!item.images.length)return <div className="gallery-empty">Case-study narrative available · Visuals to be added</div>;return <div className={`media-rail ${item.screenshots?"screenshots":""}`} aria-label={`${item.title} image gallery`}>{item.images.map((src,i)=><button className="media-frame" onClick={()=>onZoom(src,`${item.title} visual ${i+1}`)} key={src} aria-label={`Open ${item.title} image ${i+1}`}><img src={src} alt={`${item.title} visual ${i+1}`}/><span>View {String(i+1).padStart(2,"0")}</span></button>)}</div>}

function CaseModal({item,onClose,onZoom}:{item:PortfolioCase;onClose:()=>void;onZoom:(src:string,alt:string)=>void}){return <div className="modal-shell" role="dialog" aria-modal="true" aria-labelledby="case-title" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><article className="journal"><button className="modal-close" onClick={onClose} aria-label="Close case study">Close ×</button><header className="journal-header"><p>{item.label}{item.location?` · ${item.location}`:""}</p><span>{item.number}</span><h2 id="case-title">{item.title}</h2><p className="journal-deck">{item.summary}</p></header><Gallery item={item} onZoom={onZoom}/>{item.resources&&<section className="resource-panel"><p>Project documentation</p><div>{item.resources.map(resource=><a key={resource.title} href={resource.href} target="_blank" rel="noreferrer"><span><strong>{resource.title}</strong><small>{resource.description}</small></span><b>{resource.external?"Open link":"View PDF"} ↗</b></a>)}</div></section>}<div className="journal-body">{item.journal.map((section,i)=><section key={section.heading}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{section.heading}</h3><p>{section.text}</p></div></section>)}</div><footer className="journal-footer"><p>Olusola Ayodeji Ezekiel · Portfolio journal</p><button onClick={onClose}>Return to portfolio ↑</button></footer></article></div>}

const linkedinPosts=[
  {title:"Product management starts with the user",topic:"User centred product work",href:"https://www.linkedin.com/posts/ayodeji-ezekiel-olusola_productmanager-usercentric-uiux-activity-7484933393252700160-dq-m",text:"A reflection on why strong products begin with real user needs, clear flows and decisions that remove friction."},
  {title:"Discovery before delivery",topic:"Product discovery",href:"https://www.linkedin.com/posts/ayodeji-ezekiel-olusola_productmanager-productdiscovery-userresearch-activity-7483500408246677504-iNQa",text:"Good delivery begins with understanding the problem. This note looks at research, questions and evidence before building."},
  {title:"Cross functional work is the real work",topic:"Collaboration",href:"https://www.linkedin.com/posts/ayodeji-ezekiel-olusola_productmanager-collaboration-crossfunctionalteams-activity-7485622429994758145-HYKU",text:"Products move forward when design, engineering, business and product share context and work toward the same outcome."},
  {title:"A Product Manager is a problem solver",topic:"Product judgement",href:"https://www.linkedin.com/posts/ayodeji-ezekiel-olusola_productmanagement-problemsolving-customercentric-activity-7478764586150637568-JoTM",text:"The role is not about having every answer. It is about creating clarity, asking better questions and helping teams solve useful problems."}
];

const mentors=[
  {name:"Kemisola Adelakun",href:"https://www.linkedin.com/in/kemisola-adelakun-aanu"},
  {name:"Maxwell Adekunle"},
  {name:"Kingii Best (Axial)",href:"https://www.linkedin.com/in/best-okechukwu"}
];

export default function Home(){const [active,setActive]=useState<PortfolioCase|null>(null);const [zoom,setZoom]=useState<{src:string;alt:string}|null>(null);const [showWelcome,setShowWelcome]=useState(true);useEffect(()=>{const timer=window.setTimeout(()=>setShowWelcome(false),5200);return()=>window.clearTimeout(timer)},[]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==="Escape"){if(zoom)setZoom(null);else setActive(null)}};window.addEventListener("keydown",fn);document.body.style.overflow=active||zoom?"hidden":"";return()=>{window.removeEventListener("keydown",fn);document.body.style.overflow=""}},[active,zoom]);const openZoom=(src:string,alt:string)=>setZoom({src,alt});return <main>
  <header className="site-header"><a className="brand" href="#top"><span>OLUSOLA AYODEJI EZEKIEL</span><small>Product Manager</small></a><nav><a href="#products">Product work</a><a href="#construction">Construction</a><a href="#insights">Insights</a><a href="#about">About</a><a className="nav-cta" href="#contact">Let&apos;s talk</a></nav></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="hero-label">Product strategy · Agile delivery · Technical coordination</p><h1>I turn complex ideas into <em>products people can use.</em></h1><p className="hero-intro">I&apos;m <strong>Olusola Ayodeji Ezekiel</strong>, a Product Manager across FinTech, digital payments, eCommerce and iGaming. Before building digital products, I spent more than a decade leading residential, commercial and public construction projects. That experience shaped my discipline, technical judgement and ownership of delivery.</p><div className="hero-actions"><a className="button primary" href="#products">Explore case studies <span>↘</span></a><a className="button text" href="#contact">Start a conversation <span>↗</span></a></div><div className="hero-cv-actions" aria-label="Download curriculum vitae"><a href="/documents/olusola-ayodeji-product-manager-cv.pdf" download>Download Product Manager CV <span>↓</span></a><a href="/documents/olusola-ayodeji-construction-cv.pdf" download>Download Construction CV <span>↓</span></a></div></div><aside className="portrait-panel"><button className={`portrait-welcome ${showWelcome?"is-welcoming":""}`} onClick={()=>setShowWelcome(value=>!value)} aria-expanded={showWelcome} aria-label="Play Olusola's welcome greeting"><img src="/portfolio/bio-portrait.png" alt="Olusola Ayodeji Ezekiel"/><span className="welcome-message" aria-live="polite"><span className="wave-hand" aria-hidden="true">👋🏾</span><span><strong>Hi, welcome.</strong><small>I&apos;m Olusola Ayodeji Ezekiel.</small></span></span><span className="welcome-hint">Tap to say hello</span></button><div className="portrait-caption"><strong>4+ years</strong><span>Product management</span><strong>10+ years</strong><span>Project leadership</span></div></aside></section>
  <section className="statement"><p className="section-kicker">My point of view</p><blockquote>Good product management creates enough clarity for a team to solve the <em>right problem</em> and enough structure to deliver it well.</blockquote></section>
  <section className="section" id="products"><div className="section-heading"><div><p className="section-kicker">Selected product work</p><h2>Case studies in trust, payments and platforms.</h2></div><p>Each project is presented as a concise overview with an extended journal explaining the context, decisions, delivery process and lessons.</p></div><div className="case-list">{productCases.map(item=><article className="case-card" key={item.title}><div className="case-top"><span>{item.number}</span><p>{item.label}</p></div><div className="case-intro"><h3>{item.title}</h3><p>{item.summary}</p></div><Gallery item={item} onZoom={openZoom}/><div className="case-footer"><div className="feature-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div><button className="case-button" onClick={()=>setActive(item)}>{item.articleLabel}<span>↗</span></button></div></article>)}</div></section>
  <section className="capabilities section"><div className="section-heading compact"><div><p className="section-kicker">My product practice</p><h2>From insight to dependable delivery.</h2></div></div><div className="capability-grid">{[["Discover","Research, user needs, problem framing and market context"],["Define","Strategy, roadmaps, PRDs, journeys and acceptance criteria"],["Deliver","Backlogs, sprint planning, Scrum and cross-functional execution"],["Improve","Testing, feedback, analytics, prioritisation and optimisation"]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
  <section className="construction section" id="construction"><div className="section-heading"><div><p className="section-kicker">Construction leadership</p><h2>Delivery experience built on site.</h2></div><p>Six selected projects from more than a decade of structural supervision, multidisciplinary coordination and project leadership.</p></div><div className="construction-grid">{constructionCases.map(item=><article className="construction-card" key={item.title}><Gallery item={item} onZoom={openZoom}/><div className="construction-copy"><div className="case-top"><span>{item.number}</span><p>{item.label}</p></div><h3>{item.title}</h3><p className="location">{item.location}</p><p>{item.summary}</p><div className="feature-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div><button className="case-button" onClick={()=>setActive(item)}>{item.articleLabel}<span>↗</span></button></div></article>)}</div></section>
  <section className="about section" id="about"><div><p className="section-kicker">Professional summary</p><h2>Product thinking grounded in real-world delivery.</h2></div><div className="about-copy"><p className="lead">I am a Product Manager with experience across FinTech, digital payments, eCommerce and iGaming, backed by more than ten years leading construction and infrastructure delivery.</p><p>My earlier career progressed through site engineering, site management and project management across residential, commercial and public sector developments. I supervised structural execution, interpreted drawings, coordinated specialists, managed programmes and resources, protected quality and resolved problems where delays had real consequences.</p><p>That foundation now informs how I lead digital products. I bring structured discovery, clear documentation, technical curiosity and cross functional coordination to complex product work, from user research and roadmaps to sprint delivery, QA and optimisation.</p><div className="principles"><span>Clarity over noise</span><span>Users before assumptions</span><span>Outcomes over output</span></div></div></section>
  <section className="experience section"><div className="section-heading compact"><div><p className="section-kicker">Experience</p><h2>A cross industry journey.</h2></div></div><div className="timeline"><article><div><span>2025 to 2026</span><span>Product leadership</span></div><div><h3>Siiqo Marketplace</h3><p>Product strategy, marketplace experiences, Agile delivery and optimisation across payments, vendors, community and trust.</p></div></article><article><div><span>2025</span><span>FinTech product</span></div><div><h3>Canvoy Payment</h3><p>Product discovery, MVP definition, Jira ownership, Scrum leadership, payment flows and readiness.</p></div></article><article><div><span>Product</span><span>FinTech and iGaming</span></div><div><h3>Wayagram and BetBonanza</h3><p>Technical product coordination, production QA, social commerce, wallet and payments, plus sportsbook product experience.</p></div></article><article><div><span>10+ years</span><span>Project leadership</span></div><div><h3>Construction and infrastructure</h3><p>Site engineering and project leadership across residential, commercial and public developments.</p></div></article></div></section>
  <section className="insights section" id="insights"><div className="section-heading"><div><p className="section-kicker">LinkedIn insights</p><h2>Notes from the product journey.</h2></div><p>Short reflections on product discovery, delivery, collaboration and the everyday decisions behind useful products.</p></div><div className="insight-grid">{linkedinPosts.map((post,i)=><article key={post.href}><div><span>0{i+1}</span><small>{post.topic}</small></div><h3>{post.title}</h3><p>{post.text}</p><a href={post.href} target="_blank" rel="noreferrer">Read on LinkedIn ↗</a></article>)}</div><a className="linkedin-profile" href="https://www.linkedin.com/in/ayodeji-ezekiel-olusola/" target="_blank" rel="noreferrer">View my LinkedIn profile ↗</a></section>
  <section className="mentors section"><div className="section-heading compact"><div><p className="section-kicker">Mentors</p><h2>People who shaped the journey.</h2></div></div><div className="mentor-grid">{mentors.map((mentor,i)=><article key={mentor.name}><span>{String(i+1).padStart(2,"0")}</span><div className="mentor-initials">{mentor.name.split(" ").slice(0,2).map(part=>part[0]).join("")}</div><h3>{mentor.name}</h3><p>Mentor and valued influence on my professional growth.</p>{mentor.href&&<a className="mentor-link" href={mentor.href} target="_blank" rel="noreferrer">View LinkedIn profile ↗</a>}</article>)}</div></section>
  <section className="resume section"><div><p className="section-kicker">Curriculum vitae</p><h2>Two disciplines.<br/>One delivery mindset.</h2></div><div className="resume-cards"><a href="/documents/olusola-ayodeji-product-manager-cv.pdf" target="_blank"><span>Product</span><h3>Product Manager CV</h3><p>Product strategy, discovery, roadmaps, Agile delivery and technical coordination.</p><b>View or download PDF ↗</b></a><a href="/documents/olusola-ayodeji-construction-cv.pdf" target="_blank"><span>Construction</span><h3>Civil Engineering CV</h3><p>Site engineering, structural supervision and construction project leadership.</p><b>View or download PDF ↗</b></a></div></section>
  <section className="toolkit section"><div><p className="section-kicker">Product toolkit</p><h2>Tools support the work.<br/>Judgement drives it.</h2></div><div className="tool-cloud">{["Jira","Confluence","Trello","Notion","Miro","Figma","FigJam","Canva","Slack","RICE","MoSCoW","Scrum","APIs","QA","Analytics"].map(t=><span key={t}>{t}</span>)}</div></section>
  <section className="contact section" id="contact"><p className="section-kicker">Lagos, Nigeria · Open to opportunities and collaboration</p><h2>Let&apos;s build something useful.</h2><p>I&apos;m open to Product Manager opportunities, construction consultation and collaboration with founders, teams and organisations.</p><div className="contact-actions"><a className="button light" href="mailto:Olusola40@gmail.com">Send an email <span>↗</span></a><a className="button outline" href="https://wa.me/2349015934337" target="_blank" rel="noreferrer">WhatsApp <span>↗</span></a><a className="button outline" href="tel:+2349015934337">Call directly <span>↗</span></a><a href="https://www.linkedin.com/in/ayodeji-ezekiel-olusola/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div><p className="phone">+234 901 593 4337</p></section>
  <footer><div className="brand"><span>OLUSOLA AYODEJI EZEKIEL</span><small>Product Manager</small></div><a href="#top">Back to top ↑</a></footer>
  {active&&<CaseModal item={active} onClose={()=>setActive(null)} onZoom={openZoom}/>} {zoom&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Expanded image" onClick={()=>setZoom(null)}><button aria-label="Close image">Close ×</button><img src={zoom.src} alt={zoom.alt}/><p>{zoom.alt}</p></div>}
 </main>}
